@startuml
class NavMeshManager {
    - Start() : void
    + Update() : void
}
MonoBehaviour <|-- NavMeshManager
NavMeshManager --> "_surface" NavMeshSurface
NavMeshManager --> "mapManager" MapManager
@enduml
