@startuml
class SettingManager {
    + OnSettingPanel() : void
    + Quit() : void
    + OnHowToPanel() : void
    + OffHowToPanel() : void
}
MonoBehaviour <|-- SettingManager
SettingManager --> "howToPanel" GameObject
@enduml
